# Generated by Django 4.0 on 2021-12-31 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_date_joined_alter_user_last_login'),
        ('ledger', '0002_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='_intrest_status',
            new_name='intrest_status',
        ),
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
    ]
