# Generated by Django 4.0 on 2021-12-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_rename__intrest_status_client_intrest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile_number',
            field=models.CharField(max_length=11),
        ),
    ]
