# Generated by Django 4.0 on 2022-01-04 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_date_joined_alter_user_last_login'),
        ('ledger', '0007_alter_client_created_by_alter_firm_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trancation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date', models.TextField()),
                ('booking_date', models.DateField()),
                ('passenger_list', models.TextField(null=True)),
                ('verifed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
                ('firm', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ledger.firm')),
            ],
            options={
                'ordering': ['booking_date'],
                'unique_together': {('sector', 'amount', 'remarks', 'date', 'booking_date', 'passenger_list', 'verifed')},
            },
        ),
    ]
