# Generated by Django 4.0 on 2022-01-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_trancation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trancation',
            unique_together=set(),
        ),
    ]
