# Generated by Django 4.0 on 2022-01-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trancation',
            options={'ordering': ['booking_date'], 'permissions': (('view_ledger', 'Can View Ledger'), ('view_all_trancations', 'Can View all Trancations'))},
        ),
        migrations.AddField(
            model_name='client',
            name='intrest_day',
            field=models.IntegerField(default='0'),
        ),
    ]
