# Generated by Django 3.1.6 on 2022-02-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_auto_20220112_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trancation',
            options={'ordering': ['booking_date', 'id'], 'permissions': (('view_ledger', 'Can View Ledger'), ('view_all_trancations', 'Can View all Trancations'))},
        ),
    ]
