# Generated by Django 4.0 on 2021-12-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mob_no',
            field=models.CharField(default='', max_length=12),
        ),
    ]
